// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: options/gorm.proto

/*
Package gorm is a generated protocol buffer package.

It is generated from these files:
	options/gorm.proto

It has these top-level messages:
	GormFileOptions
	GormMessageOptions
	ExtraField
	GormFieldOptions
	OneToManyFieldOption
	BelongsToFieldOption
	HasOneFieldOption
	ManyToManyFieldOption
	AutoServerOptions
	MethodOptions
*/
package gorm

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type GormFileOptions struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GormFileOptions) Reset()                    { *m = GormFileOptions{} }
func (m *GormFileOptions) String() string            { return proto.CompactTextString(m) }
func (*GormFileOptions) ProtoMessage()               {}
func (*GormFileOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{0} }

type GormMessageOptions struct {
	Ormable          *bool         `protobuf:"varint,1,req,name=ormable" json:"ormable,omitempty"`
	Include          []*ExtraField `protobuf:"bytes,2,rep,name=include" json:"include,omitempty"`
	Table            *string       `protobuf:"bytes,3,opt,name=table" json:"table,omitempty"`
	MultiAccount     *bool         `protobuf:"varint,4,opt,name=multi_account,json=multiAccount" json:"multi_account,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GormMessageOptions) Reset()                    { *m = GormMessageOptions{} }
func (m *GormMessageOptions) String() string            { return proto.CompactTextString(m) }
func (*GormMessageOptions) ProtoMessage()               {}
func (*GormMessageOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{1} }

func (m *GormMessageOptions) GetOrmable() bool {
	if m != nil && m.Ormable != nil {
		return *m.Ormable
	}
	return false
}

func (m *GormMessageOptions) GetInclude() []*ExtraField {
	if m != nil {
		return m.Include
	}
	return nil
}

func (m *GormMessageOptions) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *GormMessageOptions) GetMultiAccount() bool {
	if m != nil && m.MultiAccount != nil {
		return *m.MultiAccount
	}
	return false
}

type ExtraField struct {
	Type             *string `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Tags             *string `protobuf:"bytes,3,opt,name=tags" json:"tags,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ExtraField) Reset()                    { *m = ExtraField{} }
func (m *ExtraField) String() string            { return proto.CompactTextString(m) }
func (*ExtraField) ProtoMessage()               {}
func (*ExtraField) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{2} }

func (m *ExtraField) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *ExtraField) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ExtraField) GetTags() string {
	if m != nil && m.Tags != nil {
		return *m.Tags
	}
	return ""
}

type GormFieldOptions struct {
	Tags             *string                `protobuf:"bytes,1,opt,name=tags" json:"tags,omitempty"`
	Drop             *bool                  `protobuf:"varint,2,opt,name=drop" json:"drop,omitempty"`
	One2Many         *OneToManyFieldOption  `protobuf:"bytes,3,opt,name=one2many" json:"one2many,omitempty"`
	BelongsTo        *BelongsToFieldOption  `protobuf:"bytes,4,opt,name=belongs_to,json=belongsTo" json:"belongs_to,omitempty"`
	HasOne           *HasOneFieldOption     `protobuf:"bytes,5,opt,name=has_one,json=hasOne" json:"has_one,omitempty"`
	Many2Many        *ManyToManyFieldOption `protobuf:"bytes,6,opt,name=many2many" json:"many2many,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *GormFieldOptions) Reset()                    { *m = GormFieldOptions{} }
func (m *GormFieldOptions) String() string            { return proto.CompactTextString(m) }
func (*GormFieldOptions) ProtoMessage()               {}
func (*GormFieldOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{3} }

func (m *GormFieldOptions) GetTags() string {
	if m != nil && m.Tags != nil {
		return *m.Tags
	}
	return ""
}

func (m *GormFieldOptions) GetDrop() bool {
	if m != nil && m.Drop != nil {
		return *m.Drop
	}
	return false
}

func (m *GormFieldOptions) GetOne2Many() *OneToManyFieldOption {
	if m != nil {
		return m.One2Many
	}
	return nil
}

func (m *GormFieldOptions) GetBelongsTo() *BelongsToFieldOption {
	if m != nil {
		return m.BelongsTo
	}
	return nil
}

func (m *GormFieldOptions) GetHasOne() *HasOneFieldOption {
	if m != nil {
		return m.HasOne
	}
	return nil
}

func (m *GormFieldOptions) GetMany2Many() *ManyToManyFieldOption {
	if m != nil {
		return m.Many2Many
	}
	return nil
}

// Default behavior for any repeated {ormable type} fields
type OneToManyFieldOption struct {
	// Default value: {typename}_{pk1}[, {typename}_{pk2}...]
	Foreignkey *string `protobuf:"bytes,1,opt,name=foreignkey" json:"foreignkey,omitempty"`
	// Default value: {pk1}[, {pk2}...]
	AssociationForeignkey *string `protobuf:"bytes,2,opt,name=association_foreignkey,json=associationForeignkey" json:"association_foreignkey,omitempty"`
	// If set will add this field, and R ordered based on this field, and W
	// after setting the field sequentially
	PositionField    *string `protobuf:"bytes,3,opt,name=position_field,json=positionField" json:"position_field,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OneToManyFieldOption) Reset()                    { *m = OneToManyFieldOption{} }
func (m *OneToManyFieldOption) String() string            { return proto.CompactTextString(m) }
func (*OneToManyFieldOption) ProtoMessage()               {}
func (*OneToManyFieldOption) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{4} }

func (m *OneToManyFieldOption) GetForeignkey() string {
	if m != nil && m.Foreignkey != nil {
		return *m.Foreignkey
	}
	return ""
}

func (m *OneToManyFieldOption) GetAssociationForeignkey() string {
	if m != nil && m.AssociationForeignkey != nil {
		return *m.AssociationForeignkey
	}
	return ""
}

func (m *OneToManyFieldOption) GetPositionField() string {
	if m != nil && m.PositionField != nil {
		return *m.PositionField
	}
	return ""
}

type BelongsToFieldOption struct {
	// Default value: {child_typename}_{pk1}[, {child_typename}_{pk2} ...]
	Foreignkey *string `protobuf:"bytes,1,opt,name=foreignkey" json:"foreignkey,omitempty"`
	// Default value: {pk1}[, {pk2} ...]
	AssociationForeignkey *string `protobuf:"bytes,2,opt,name=association_foreignkey,json=associationForeignkey" json:"association_foreignkey,omitempty"`
	XXX_unrecognized      []byte  `json:"-"`
}

func (m *BelongsToFieldOption) Reset()                    { *m = BelongsToFieldOption{} }
func (m *BelongsToFieldOption) String() string            { return proto.CompactTextString(m) }
func (*BelongsToFieldOption) ProtoMessage()               {}
func (*BelongsToFieldOption) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{5} }

func (m *BelongsToFieldOption) GetForeignkey() string {
	if m != nil && m.Foreignkey != nil {
		return *m.Foreignkey
	}
	return ""
}

func (m *BelongsToFieldOption) GetAssociationForeignkey() string {
	if m != nil && m.AssociationForeignkey != nil {
		return *m.AssociationForeignkey
	}
	return ""
}

// Default behavior for any non-repeated {ormable type} fields
type HasOneFieldOption struct {
	// Default value: {child_typename}_{pk1}[, {child_typename}_{pk2} ...]
	Foreignkey *string `protobuf:"bytes,1,opt,name=foreignkey" json:"foreignkey,omitempty"`
	// Default value: {pk1}[, {pk2} ...]
	AssociationForeignkey *string `protobuf:"bytes,2,opt,name=association_foreignkey,json=associationForeignkey" json:"association_foreignkey,omitempty"`
	XXX_unrecognized      []byte  `json:"-"`
}

func (m *HasOneFieldOption) Reset()                    { *m = HasOneFieldOption{} }
func (m *HasOneFieldOption) String() string            { return proto.CompactTextString(m) }
func (*HasOneFieldOption) ProtoMessage()               {}
func (*HasOneFieldOption) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{6} }

func (m *HasOneFieldOption) GetForeignkey() string {
	if m != nil && m.Foreignkey != nil {
		return *m.Foreignkey
	}
	return ""
}

func (m *HasOneFieldOption) GetAssociationForeignkey() string {
	if m != nil && m.AssociationForeignkey != nil {
		return *m.AssociationForeignkey
	}
	return ""
}

type ManyToManyFieldOption struct {
	// Default value: {typename}_{child_typename}
	Jointable *string `protobuf:"bytes,1,opt,name=jointable" json:"jointable,omitempty"`
	// Default value: {child_typename}_{pk1}[, {child_typename}_{pk2} ...]
	Foreignkey *string `protobuf:"bytes,2,opt,name=foreignkey" json:"foreignkey,omitempty"`
	// Default value: {pk1}[, {pk2} ...]
	AssociationForeignkey *string `protobuf:"bytes,3,opt,name=association_foreignkey,json=associationForeignkey" json:"association_foreignkey,omitempty"`
	//
	JointableForeignkey            *string `protobuf:"bytes,4,opt,name=jointable_foreignkey,json=jointableForeignkey" json:"jointable_foreignkey,omitempty"`
	AssociationJointableForeignkey *string `protobuf:"bytes,5,opt,name=association_jointable_foreignkey,json=associationJointableForeignkey" json:"association_jointable_foreignkey,omitempty"`
	XXX_unrecognized               []byte  `json:"-"`
}

func (m *ManyToManyFieldOption) Reset()                    { *m = ManyToManyFieldOption{} }
func (m *ManyToManyFieldOption) String() string            { return proto.CompactTextString(m) }
func (*ManyToManyFieldOption) ProtoMessage()               {}
func (*ManyToManyFieldOption) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{7} }

func (m *ManyToManyFieldOption) GetJointable() string {
	if m != nil && m.Jointable != nil {
		return *m.Jointable
	}
	return ""
}

func (m *ManyToManyFieldOption) GetForeignkey() string {
	if m != nil && m.Foreignkey != nil {
		return *m.Foreignkey
	}
	return ""
}

func (m *ManyToManyFieldOption) GetAssociationForeignkey() string {
	if m != nil && m.AssociationForeignkey != nil {
		return *m.AssociationForeignkey
	}
	return ""
}

func (m *ManyToManyFieldOption) GetJointableForeignkey() string {
	if m != nil && m.JointableForeignkey != nil {
		return *m.JointableForeignkey
	}
	return ""
}

func (m *ManyToManyFieldOption) GetAssociationJointableForeignkey() string {
	if m != nil && m.AssociationJointableForeignkey != nil {
		return *m.AssociationJointableForeignkey
	}
	return ""
}

type AutoServerOptions struct {
	Autogen          *bool  `protobuf:"varint,1,opt,name=autogen" json:"autogen,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AutoServerOptions) Reset()                    { *m = AutoServerOptions{} }
func (m *AutoServerOptions) String() string            { return proto.CompactTextString(m) }
func (*AutoServerOptions) ProtoMessage()               {}
func (*AutoServerOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{8} }

func (m *AutoServerOptions) GetAutogen() bool {
	if m != nil && m.Autogen != nil {
		return *m.Autogen
	}
	return false
}

type MethodOptions struct {
	ObjectType       *string `protobuf:"bytes,1,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MethodOptions) Reset()                    { *m = MethodOptions{} }
func (m *MethodOptions) String() string            { return proto.CompactTextString(m) }
func (*MethodOptions) ProtoMessage()               {}
func (*MethodOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{9} }

func (m *MethodOptions) GetObjectType() string {
	if m != nil && m.ObjectType != nil {
		return *m.ObjectType
	}
	return ""
}

var E_FileOpts = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*GormFileOptions)(nil),
	Field:         52119,
	Name:          "gorm.file_opts",
	Tag:           "bytes,52119,opt,name=file_opts,json=fileOpts",
	Filename:      "options/gorm.proto",
}

var E_Opts = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*GormMessageOptions)(nil),
	Field:         52119,
	Name:          "gorm.opts",
	Tag:           "bytes,52119,opt,name=opts",
	Filename:      "options/gorm.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*GormFieldOptions)(nil),
	Field:         52119,
	Name:          "gorm.field",
	Tag:           "bytes,52119,opt,name=field",
	Filename:      "options/gorm.proto",
}

var E_Server = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*AutoServerOptions)(nil),
	Field:         52119,
	Name:          "gorm.server",
	Tag:           "bytes,52119,opt,name=server",
	Filename:      "options/gorm.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*MethodOptions)(nil),
	Field:         52119,
	Name:          "gorm.method",
	Tag:           "bytes,52119,opt,name=method",
	Filename:      "options/gorm.proto",
}

func init() {
	proto.RegisterType((*GormFileOptions)(nil), "gorm.GormFileOptions")
	proto.RegisterType((*GormMessageOptions)(nil), "gorm.GormMessageOptions")
	proto.RegisterType((*ExtraField)(nil), "gorm.ExtraField")
	proto.RegisterType((*GormFieldOptions)(nil), "gorm.GormFieldOptions")
	proto.RegisterType((*OneToManyFieldOption)(nil), "gorm.OneToManyFieldOption")
	proto.RegisterType((*BelongsToFieldOption)(nil), "gorm.BelongsToFieldOption")
	proto.RegisterType((*HasOneFieldOption)(nil), "gorm.HasOneFieldOption")
	proto.RegisterType((*ManyToManyFieldOption)(nil), "gorm.ManyToManyFieldOption")
	proto.RegisterType((*AutoServerOptions)(nil), "gorm.AutoServerOptions")
	proto.RegisterType((*MethodOptions)(nil), "gorm.MethodOptions")
	proto.RegisterExtension(E_FileOpts)
	proto.RegisterExtension(E_Opts)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Server)
	proto.RegisterExtension(E_Method)
}

func init() { proto.RegisterFile("options/gorm.proto", fileDescriptorGorm) }

var fileDescriptorGorm = []byte{
	// 708 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x5f, 0x4b, 0x1b, 0x4f,
	0x14, 0x25, 0x31, 0x89, 0xc9, 0xf5, 0xe7, 0xaf, 0x3a, 0x46, 0xbb, 0x58, 0xab, 0x61, 0x4b, 0x21,
	0x14, 0x4c, 0xac, 0xb4, 0x82, 0xe9, 0x93, 0x42, 0xad, 0x14, 0x42, 0x60, 0xeb, 0x53, 0x5f, 0xc2,
	0x66, 0x33, 0xd9, 0xac, 0xdd, 0x9d, 0xbb, 0xec, 0x4c, 0x8a, 0xf9, 0x08, 0x7d, 0x6f, 0x11, 0xfa,
	0x69, 0xcb, 0xcc, 0xec, 0x9f, 0xd1, 0x2c, 0x85, 0x3e, 0xf8, 0x36, 0x73, 0xf6, 0x9c, 0x33, 0xe7,
	0xde, 0x61, 0xee, 0x02, 0xc1, 0x58, 0x04, 0xc8, 0x78, 0xdf, 0xc7, 0x24, 0xea, 0xc5, 0x09, 0x0a,
	0x24, 0x35, 0xb9, 0xde, 0xef, 0xf8, 0x88, 0x7e, 0x48, 0xfb, 0x0a, 0x9b, 0x2c, 0x66, 0xfd, 0x29,
	0xe5, 0x5e, 0x12, 0xc4, 0x02, 0x13, 0xcd, 0xb3, 0xb7, 0xe1, 0xd9, 0x27, 0x4c, 0xa2, 0xab, 0x20,
	0xa4, 0x23, 0xed, 0x62, 0xff, 0xaa, 0x00, 0x91, 0xd8, 0x90, 0x72, 0xee, 0xfa, 0x19, 0x4c, 0x2c,
	0x58, 0xc7, 0x24, 0x72, 0x27, 0x21, 0xb5, 0x2a, 0x9d, 0x6a, 0xb7, 0xe9, 0x64, 0x5b, 0xf2, 0x06,
	0xd6, 0x03, 0xe6, 0x85, 0x8b, 0x29, 0xb5, 0xaa, 0x9d, 0xb5, 0xee, 0xc6, 0xe9, 0x56, 0x4f, 0x25,
	0xf9, 0x78, 0x27, 0x12, 0xf7, 0x2a, 0xa0, 0xe1, 0xd4, 0xc9, 0x08, 0xa4, 0x0d, 0x75, 0xa1, 0x3c,
	0xd6, 0x3a, 0x95, 0x6e, 0xcb, 0xd1, 0x1b, 0xf2, 0x0a, 0x36, 0xa3, 0x45, 0x28, 0x82, 0xb1, 0xeb,
	0x79, 0xb8, 0x60, 0xc2, 0xaa, 0x75, 0x2a, 0xdd, 0xa6, 0xf3, 0x9f, 0x02, 0x2f, 0x34, 0x66, 0x5f,
	0x03, 0x14, 0x8e, 0x84, 0x40, 0x4d, 0x2c, 0x63, 0x9d, 0xa5, 0xe5, 0xa8, 0xb5, 0xc4, 0x98, 0x1b,
	0xc9, 0x14, 0x0a, 0x93, 0x6b, 0xc5, 0x73, 0x7d, 0x9e, 0x9e, 0xa7, 0xd6, 0xf6, 0xef, 0x2a, 0x6c,
	0xe9, 0xaa, 0x69, 0x38, 0xcd, 0xea, 0xcb, 0x88, 0x95, 0x82, 0x28, 0xb1, 0x69, 0x82, 0xb1, 0x55,
	0x55, 0x71, 0xd4, 0x9a, 0x9c, 0x41, 0x13, 0x19, 0x3d, 0x8d, 0x5c, 0xb6, 0x54, 0xa6, 0x1b, 0xa7,
	0xfb, 0xba, 0xdc, 0x11, 0xa3, 0x37, 0x38, 0x74, 0xd9, 0xd2, 0xb0, 0x75, 0x72, 0x2e, 0x39, 0x07,
	0x98, 0xd0, 0x10, 0x99, 0xcf, 0xc7, 0x02, 0x55, 0x81, 0xb9, 0xf2, 0x52, 0xe3, 0x37, 0x68, 0x2a,
	0x5b, 0x93, 0x0c, 0x25, 0x27, 0xb0, 0x3e, 0x77, 0xf9, 0x18, 0x19, 0xb5, 0xea, 0x4a, 0xf7, 0x5c,
	0xeb, 0xae, 0x5d, 0x3e, 0x62, 0xd4, 0x14, 0x35, 0xe6, 0x0a, 0x22, 0xe7, 0xd0, 0x92, 0x87, 0xea,
	0x94, 0x0d, 0xa5, 0x79, 0xa1, 0x35, 0x32, 0xe0, 0x6a, 0xcc, 0x82, 0x6d, 0xff, 0xac, 0x40, 0xbb,
	0xac, 0x14, 0x72, 0x08, 0x30, 0xc3, 0x84, 0x06, 0x3e, 0xfb, 0x46, 0x97, 0x69, 0x9b, 0x0c, 0x84,
	0xbc, 0x87, 0x3d, 0x97, 0x73, 0xf4, 0x02, 0x57, 0xd2, 0xc7, 0x06, 0xb7, 0xaa, 0xb8, 0xbb, 0xc6,
	0xd7, 0xab, 0x42, 0xf6, 0x1a, 0xfe, 0x8f, 0x91, 0x07, 0x5a, 0x23, 0x8f, 0x4b, 0xaf, 0x6a, 0x33,
	0x43, 0x55, 0x06, 0x3b, 0x82, 0x76, 0x59, 0x9b, 0x9e, 0x28, 0x95, 0x7d, 0x0b, 0xdb, 0x2b, 0xdd,
	0x7d, 0xaa, 0xb3, 0x7e, 0x54, 0x61, 0xb7, 0xf4, 0x5a, 0xc8, 0x01, 0xb4, 0x6e, 0x31, 0x60, 0x22,
	0x7d, 0x75, 0xd2, 0xa3, 0x00, 0x1e, 0xc5, 0xa9, 0xfe, 0x43, 0x9c, 0xb5, 0xbf, 0x5d, 0xc8, 0x5b,
	0x68, 0xe7, 0x67, 0x98, 0xa2, 0x9a, 0x12, 0xed, 0xe4, 0xdf, 0x0c, 0xc9, 0x35, 0x74, 0xcc, 0x93,
	0x4a, 0xe5, 0x75, 0x25, 0x3f, 0x34, 0x78, 0x9f, 0x57, 0x9d, 0xec, 0x63, 0xd8, 0xbe, 0x58, 0x08,
	0xfc, 0x42, 0x93, 0xef, 0x34, 0x31, 0x46, 0x8f, 0xbb, 0x10, 0xe8, 0x53, 0xa6, 0x9a, 0xd0, 0x74,
	0xb2, 0xad, 0x7d, 0x02, 0x9b, 0x43, 0x2a, 0xe6, 0x98, 0xbf, 0xe2, 0x23, 0xd8, 0xc0, 0xc9, 0x2d,
	0xf5, 0xc4, 0x38, 0x9d, 0x0e, 0xaa, 0x29, 0x1a, 0xba, 0x59, 0xc6, 0x74, 0xe0, 0x40, 0x6b, 0x16,
	0x84, 0x74, 0x8c, 0xb1, 0xe0, 0xe4, 0xa0, 0xa7, 0x07, 0x64, 0x2f, 0x1b, 0x90, 0x3d, 0x63, 0x10,
	0x5a, 0xf7, 0xf7, 0xfa, 0x7d, 0xef, 0xea, 0x97, 0xf3, 0x68, 0x4e, 0x3a, 0xcd, 0x99, 0xde, 0xf0,
	0xc1, 0x08, 0x6a, 0xca, 0xee, 0x68, 0xc5, 0xee, 0xe1, 0x0c, 0xcd, 0x1d, 0xad, 0xc2, 0xf1, 0x21,
	0xc3, 0x51, 0x46, 0x83, 0x21, 0xd4, 0xd5, 0x53, 0x20, 0x2f, 0x4b, 0x02, 0x16, 0x33, 0x2b, 0xf7,
	0xdb, 0x33, 0x13, 0x16, 0xdf, 0x1d, 0xed, 0x32, 0x70, 0xa0, 0xc1, 0x55, 0x43, 0x4b, 0x12, 0xca,
	0x4e, 0x07, 0xde, 0x4a, 0xc2, 0x74, 0xc2, 0xac, 0xdc, 0x85, 0x93, 0x3a, 0x0d, 0x86, 0xd0, 0x88,
	0x54, 0xe7, 0xc9, 0x61, 0x49, 0xd5, 0xc6, 0x95, 0xe4, 0x96, 0x3b, 0xe9, 0x00, 0x32, 0x3f, 0x3a,
	0xa9, 0xc9, 0xe5, 0xd9, 0xd7, 0x77, 0x7e, 0x20, 0xe6, 0x8b, 0x49, 0xcf, 0xc3, 0xa8, 0x1f, 0xb0,
	0x19, 0x4e, 0x42, 0xbc, 0xc3, 0x98, 0x32, 0xfd, 0xf3, 0xf2, 0x8e, 0x7d, 0xca, 0x8e, 0xa5, 0x41,
	0x3f, 0xfd, 0xdb, 0x7d, 0x90, 0x9b, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xcc, 0xaf, 0xa2,
	0xfc, 0x06, 0x00, 0x00,
}
